Repository discord-net/Discord.Net, pull requests merged in 2019-06, with the labels that each got.

#1311 Feature: Disconnect guild members from voice channels
  src/Discord.Net.Core/Entities/Users/GuildUserProperties.cs
  src/Discord.Net.Rest/API/Rest/ModifyGuildMemberParams.cs
  src/Discord.Net.Rest/Entities/Users/UserHelper.cs
Labels: version: patch

#1323 Fixed optionals having IsSpecified true when objects weren't in cache
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
Labels: priority: bug, project: websocket, version: patch

#1237 Fix #1233, Add properties missing from User and Activity models
  src/Discord.Net.Core/Entities/Activities/ActivityProperties.cs
  src/Discord.Net.Core/Entities/Activities/Game.cs
  src/Discord.Net.Core/Entities/Activities/IActivity.cs
  src/Discord.Net.Core/Entities/Activities/RichGame.cs
  src/Discord.Net.Core/Entities/Users/ISelfUser.cs
  src/Discord.Net.Core/Entities/Users/PremiumType.cs
  src/Discord.Net.Core/Entities/Users/UserProperties.cs
  src/Discord.Net.Rest/API/Common/Game.cs
  src/Discord.Net.Rest/API/Common/User.cs
  src/Discord.Net.Rest/Entities/Users/RestSelfUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketSelfUser.cs
  src/Discord.Net.WebSocket/Extensions/EntityExtensions.cs
Labels: version: minor

#1310 Added id overload for RemoveReactionAsync
  src/Discord.Net.Core/Entities/Messages/IUserMessage.cs
  src/Discord.Net.Rest/Entities/Messages/MessageHelper.cs
  src/Discord.Net.Rest/Entities/Messages/RestUserMessage.cs
  src/Discord.Net.WebSocket/Entities/Messages/SocketUserMessage.cs
Labels: project: core, version: minor

#1247 Implement Client Status Support
  src/Discord.Net.Core/Entities/Users/ClientType.cs
  src/Discord.Net.Core/Entities/Users/IPresence.cs
  src/Discord.Net.Rest/API/Common/Presence.cs
  src/Discord.Net.Rest/Entities/Users/RestUser.cs
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketPresence.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketUnknownUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketWebhookUser.cs
Labels: priority: improvement, project: core, version: major

#1337 Fixed attempting to access a non-present optional value
  src/Discord.Net.Rest/Entities/Messages/RestMessage.cs
Labels: priority: bug, version: patch

#1333 Remove null coalescing on ToEmbedBuilder Color
  src/Discord.Net.Core/Extensions/EmbedBuilderExtensions.cs
Labels: priority: bug
