Repository discord-net/Discord.Net, pull requests merged in 2021-11, with the labels that each got.

#1941 Fix emote TryParse
  src/Discord.Net.Core/Entities/Emotes/Emote.cs
Labels: version: patch

#1865 Add null check to AllowedMentions.ToModel()
  src/Discord.Net.Rest/Extensions/EntityExtensions.cs
Labels: V3 Todo

#1861 fix: Add MaxBitrate to the interface
  src/Discord.Net.Core/Entities/Guilds/IGuild.cs
  src/Discord.Net.Rest/Entities/Guilds/RestGuild.cs
  src/Discord.Net.WebSocket/Entities/Guilds/SocketGuild.cs
Labels: V3 Todo

#1666 Added negative TimeSpan handling
  src/Discord.Net.Commands/Readers/TimeSpanTypeReader.cs
  test/Discord.Net.Tests.Unit/TimeSpanTypeReaderTests.cs
Labels: version: major, V3 Todo

#1518 Add default nullable enum typereader
  src/Discord.Net.Commands/CommandService.cs
Labels: project: commands, priority: improvement, V3 Todo

#1942 feature: Support to multiple files for Webhooks
  src/Discord.Net.Rest/API/Rest/UploadWebhookFileParams.cs
  src/Discord.Net.Webhook/DiscordWebhookClient.cs
  src/Discord.Net.Webhook/WebhookClientHelper.cs
Labels: enhancement, V3 Todo

#1944 Add Voice binaries
  docs/guides/voice/sending-voice.md
  voice-natives/README.md
  voice-natives/vnext_natives_win32_x64.zip
  voice-natives/vnext_natives_win32_x86.zip
Labels: project: docs, priority: critical, V3 Todo

#1947 Fix CurrentUser with ICommandContext on ShardedClient is broken
  src/Discord.Net.WebSocket/DiscordShardedClient.cs
Labels: bug

#1946 Fix NRE when adding parameters thru builders
  src/Discord.Net.Commands/Builders/ParameterBuilder.cs
Labels: priority: bug, V3 Todo

#1943 feature: Handle bidirectional usernames
  src/Discord.Net.Core/Format.cs
  src/Discord.Net.Rest/Entities/Users/RestUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketUser.cs
Labels: enhancement, V3 Todo

#1945 feature: Add presence specific event
  src/Discord.Net.Core/Entities/Users/IPresence.cs
  src/Discord.Net.Rest/Entities/Users/RestUser.cs
  src/Discord.Net.WebSocket/BaseSocketClient.Events.cs
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketGlobalUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketGuildUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketPresence.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketUser.cs
Labels: priority: improvement, V3 Todo

#1700 Implementation of ValidateAndGetBestMatch
  src/Discord.Net.Commands/CommandService.cs
  src/Discord.Net.Commands/Results/MatchResult.cs
Labels: enhancement, priority: improvement, V3 Todo

#1949 feature: default application games
  src/Discord.Net.Core/Discord.Net.Core.csproj
  src/Discord.Net.Core/Entities/Activities/DefaultApplications.cs
  src/Discord.Net.Core/Entities/Channels/INestedChannel.cs
  src/Discord.Net.Rest/Entities/Channels/RestTextChannel.cs
  src/Discord.Net.Rest/Entities/Channels/RestVoiceChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketTextChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketVoiceChannel.cs
  test/Discord.Net.Tests.Unit/MockedEntities/MockedTextChannel.cs
  test/Discord.Net.Tests.Unit/MockedEntities/MockedVoiceChannel.cs
Labels: enhancement, priority: improvement, V3 Todo

#1948 feature: warn on invalid gateway intents
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
  src/Discord.Net.WebSocket/DiscordSocketConfig.cs
Labels: project: websocket, priority: improvement, V3 Todo

#1152 Add characters commonly used in links to Sanitize
  src/Discord.Net.Core/Format.cs
Labels: V3 Todo

#1767 feature: Add method to clear guild user cache
  src/Discord.Net.WebSocket/ClientState.cs
  src/Discord.Net.WebSocket/Entities/Guilds/SocketGuild.cs
Labels: lib feature, V3 Todo
