Repository discord-net/Discord.Net, pull requests merged in 2021-12, with the labels that each got.

#1950 Add custom setter to Group property of ModuleBuilder to automatically invoke AddAliases
  src/Discord.Net.Commands/Builders/ModuleBuilder.cs
  src/Discord.Net.Commands/Builders/ModuleClassBuilder.cs
Labels: project: commands, priority: bug, V3 Todo

#1959 Change required to isRequired
  src/Discord.Net.Core/Entities/Interactions/SlashCommands/SlashCommandBuilder.cs
Labels: V3 Todo

#1970 Fix NRE on http error handling
  src/Discord.Net.Rest/Net/Queue/RequestQueueBucket.cs
Labels: bug, project: rest, V3 Todo

#1971 Update to Labs 3.5.0
  docs/faq/basics/basic-operations.md
  docs/guides/getting_started/installing.md
  docs/guides/v2_v3_guide/v2_to_v3_guide.md
  docs/index.md
  src/Discord.Net.Commands/CommandService.cs
  src/Discord.Net.Commands/Discord.Net.Commands.csproj
  src/Discord.Net.Core/Discord.Net.Core.csproj
  src/Discord.Net.Core/DiscordErrorCode.cs
  src/Discord.Net.Core/Entities/IApplication.cs
  src/Discord.Net.Core/Entities/Interactions/IDiscordInteraction.cs
  src/Discord.Net.Core/Entities/Messages/FileAttachment.cs
  src/Discord.Net.Core/Interactions/IRestInteractionContext.cs
  src/Discord.Net.Interactions/Attributes/Preconditions/RequireBotPermissionAttribute.cs
  src/Discord.Net.Interactions/Attributes/Preconditions/RequireContextAttribute.cs
  src/Discord.Net.Interactions/Attributes/Preconditions/RequireNsfwAttribute.cs
  src/Discord.Net.Interactions/Attributes/Preconditions/RequireOwnerAttribute.cs
  src/Discord.Net.Interactions/Attributes/Preconditions/RequireRoleAttribute.cs
  src/Discord.Net.Interactions/Attributes/Preconditions/RequireUserPermissionAttribute.cs
  src/Discord.Net.Interactions/AutocompleteHandlers/AutocompleteHandler.cs
  src/Discord.Net.Interactions/Discord.Net.Interactions.csproj
  src/Discord.Net.Interactions/RestInteractionModuleBase.cs
  src/Discord.Net.Rest/API/Common/Application.cs
  src/Discord.Net.Rest/API/Rest/UploadInteractionFileParams.cs
  src/Discord.Net.Rest/Discord.Net.Rest.csproj
  src/Discord.Net.Rest/DiscordRestApiClient.cs
  src/Discord.Net.Rest/Entities/Channels/ChannelHelper.cs
  src/Discord.Net.Rest/Entities/Interactions/InteractionHelper.cs
  src/Discord.Net.Rest/Entities/Interactions/RestInteraction.cs
  src/Discord.Net.Rest/Entities/Messages/RestInteractionMessage.cs
  src/Discord.Net.Rest/Entities/RestApplication.cs
  src/Discord.Net.Rest/Interactions/RestInteractionContext.cs
  src/Discord.Net.Rest/Net/DefaultRestClient.cs
  src/Discord.Net.Rest/Net/Queue/RequestQueueBucket.cs
  src/Discord.Net.WebSocket/BaseSocketClient.Events.cs
  src/Discord.Net.WebSocket/DiscordShardedClient.cs
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
  src/Discord.Net.WebSocket/Entities/Interaction/MessageComponents/SocketMessageComponent.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SlashCommands/SocketAutocompleteInteraction.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketBaseCommand/SocketCommandBase.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketInteraction.cs
  src/Discord.Net.Webhook/Discord.Net.Webhook.csproj
Labels: V3 Todo

#1888 Allow clients to send 'Gateway Voice State Update' command
  src/Discord.Net.Core/Entities/Channels/AudioChannelProperties.cs
  src/Discord.Net.Core/Entities/Channels/IAudioChannel.cs
  src/Discord.Net.Rest/Entities/Channels/RestGroupChannel.cs
  src/Discord.Net.Rest/Entities/Channels/RestVoiceChannel.cs
  src/Discord.Net.WebSocket/DiscordSocketApiClient.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketGroupChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketVoiceChannel.cs
  src/Discord.Net.WebSocket/Entities/Guilds/SocketGuild.cs
  test/Discord.Net.Tests.Unit/MockedEntities/MockedGroupChannel.cs
  test/Discord.Net.Tests.Unit/MockedEntities/MockedVoiceChannel.cs
Labels: enhancement, V3 Todo

#1977 fix: Thread member update NRE
  src/Discord.Net.Rest/API/Common/ThreadMember.cs
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketThreadUser.cs
Labels: bug

#1980 Fix RequireRole Attribute of Interaction Service
  src/Discord.Net.Interactions/Attributes/Preconditions/RequireRoleAttribute.cs
Labels: bug

#1976 fix: guild scheduled events update
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
  src/Discord.Net.WebSocket/Entities/Guilds/SocketGuildEvent.cs
Labels: bug
