Repository discord-net/Discord.Net, pull requests merged in 2022-02, with the labels that each got.

#2077 Patch; Clone being created on updated entity
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketGlobalUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketGroupUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketGuildUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketSelfUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketThreadUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketUnknownUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketWebhookUser.cs
Labels: bug

#2076 Patch; Rest message components cannot pass through execute method
  src/Discord.Net.Interactions/Info/Commands/ComponentCommandInfo.cs
Labels: bug

#1713 Simplify code in Discord.DiscordComparers
  src/Discord.Net.Core/Utils/Comparers.cs
Labels: project: core

#2079 Feature: Add IEnumerable collection parameters instead of arrays
  src/Discord.Net.Core/Extensions/MessageExtensions.cs
Labels: enhancement

#2092 Fix Current user null on reconnect
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
Labels: bug, enhancement

#2091 Fix: modifying interaction attachments
  src/Discord.Net.Interactions/InteractionModuleBase.cs
  src/Discord.Net.Rest/DiscordRestApiClient.cs
  src/Discord.Net.Rest/Entities/Interactions/InteractionHelper.cs
Labels: enhancement

#2090 Fix attempts to fetch channels in interactions
  src/Discord.Net.Rest/Entities/Interactions/RestInteraction.cs
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketInteraction.cs
Labels: project: rest, project: websocket

#2089 Fix guild feature enum mixing ints
  src/Discord.Net.Core/Entities/Guilds/GuildFeature.cs
Labels: project: core

#2088 Feature: Slash command file parameter
  src/Discord.Net.Core/Entities/Interactions/ApplicationCommandOptionType.cs
  src/Discord.Net.Interactions/InteractionService.cs
  src/Discord.Net.Interactions/TypeConverters/DefaultEntityTypeConverter.cs
  src/Discord.Net.Rest/API/Common/ApplicationCommandInteractionDataResolved.cs
  src/Discord.Net.Rest/Entities/Interactions/CommandBase/RestResolvableData.cs
  src/Discord.Net.Rest/Entities/Interactions/SlashCommands/RestSlashCommandDataOption.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SlashCommands/SocketSlashCommandDataOption.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketBaseCommand/SocketResolvableData.cs
Labels: enhancement, discord feature, version: minor

#2098 Fix channel being null in most cases on Interactions
  src/Discord.Net.Core/Entities/Interactions/IDiscordInteraction.cs
  src/Discord.Net.Interactions/Attributes/Preconditions/RequireContextAttribute.cs
  src/Discord.Net.Rest/Entities/Interactions/RestInteraction.cs
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
  src/Discord.Net.WebSocket/Entities/Interaction/ContextMenuCommands/MessageCommands/SocketMessageCommand.cs
  src/Discord.Net.WebSocket/Entities/Interaction/ContextMenuCommands/UserCommands/SocketUserCommand.cs
  src/Discord.Net.WebSocket/Entities/Interaction/MessageComponents/SocketMessageComponent.cs
  src/Discord.Net.WebSocket/Entities/Interaction/Modals/SocketModal.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SlashCommands/SocketAutocompleteInteraction.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SlashCommands/SocketSlashCommand.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketBaseCommand/SocketCommandBase.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketInteraction.cs
Labels: priority: critical

#2099 Update interaction summaries
  src/Discord.Net.Core/Entities/Interactions/IDiscordInteraction.cs
  src/Discord.Net.Rest/Entities/Interactions/CommandBase/RestCommandBase.cs
  src/Discord.Net.Rest/Entities/Interactions/ContextMenuCommands/MessageCommands/RestMessageCommand.cs
  src/Discord.Net.Rest/Entities/Interactions/ContextMenuCommands/MessageCommands/RestMessageCommandData.cs
  src/Discord.Net.Rest/Entities/Interactions/ContextMenuCommands/UserCommands/RestUserCommandData.cs
  src/Discord.Net.Rest/Entities/Interactions/MessageComponents/RestMessageComponentData.cs
  src/Discord.Net.Rest/Entities/Interactions/RestApplicationCommand.cs
  src/Discord.Net.Rest/Entities/Interactions/RestApplicationCommandOption.cs
  src/Discord.Net.Rest/Entities/Interactions/RestGuildCommand.cs
  src/Discord.Net.Rest/Entities/Interactions/RestInteraction.cs
  src/Discord.Net.Rest/Entities/Interactions/SlashCommands/RestAutocompleteInteractionData.cs
  src/Discord.Net.WebSocket/Entities/Interaction/ContextMenuCommands/MessageCommands/SocketMessageCommand.cs
  src/Discord.Net.WebSocket/Entities/Interaction/Modals/SocketModal.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SlashCommands/SocketAutocompleteInteraction.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SlashCommands/SocketAutocompleteInteractionData.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SlashCommands/SocketSlashCommand.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SlashCommands/SocketSlashCommandDataOption.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketBaseCommand/SocketApplicationCommand.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketBaseCommand/SocketApplicationCommandOption.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketBaseCommand/SocketCommandBase.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketBaseCommand/SocketCommandBaseData.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketInteraction.cs
Labels: project: docs

#2100 Fix crosspost ratelimits
  src/Discord.Net.Rest/API/Common/Ratelimit.cs
  src/Discord.Net.Rest/Net/DefaultRestClient.cs
  src/Discord.Net.Rest/Net/Queue/RequestQueueBucket.cs
  src/Discord.Net.Rest/Net/RateLimitInfo.cs
Labels: priority: critical

#2110 fix: Implement correct ratelimit handles for 429's
  src/Discord.Net.Rest/Net/Queue/RequestQueueBucket.cs
  src/Discord.Net.Rest/Net/RateLimitInfo.cs
Labels: priority: critical

#2116 Revert "Fixes unused creation of REST clients for DiscordShardedClient shards."
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
Labels: priority: critical

#2117 fix: stream access exception when ratelimited
  src/Discord.Net.Rest/Net/Queue/RequestQueueBucket.cs
Labels: priority: bug
