Repository discord-net/Discord.Net, pull requests merged in 2022-05, with the labels that each got.

#2283 Support FailIfNotExists on MessageReference
  src/Discord.Net.Core/Entities/Messages/MessageReference.cs
  src/Discord.Net.Rest/API/Common/MessageReference.cs
  src/Discord.Net.Rest/Entities/Messages/RestMessage.cs
  src/Discord.Net.Rest/Extensions/EntityExtensions.cs
  src/Discord.Net.WebSocket/Entities/Messages/SocketMessage.cs
Labels: enhancement

#2270 Treat warnings as errors and set warning level to 5
  src/Discord.Net.Commands/Discord.Net.Commands.csproj
  src/Discord.Net.Commands/Results/MatchResult.cs
  src/Discord.Net.Core/Discord.Net.Core.csproj
  src/Discord.Net.Core/Entities/Guilds/IGuild.cs
  src/Discord.Net.Core/Entities/Guilds/IGuildScheduledEvent.cs
  src/Discord.Net.Core/Entities/Interactions/ApplicationCommandOptionType.cs
  src/Discord.Net.Core/Entities/Interactions/IDiscordInteraction.cs
  src/Discord.Net.Core/Entities/Interactions/MessageComponents/ComponentBuilder.cs
  src/Discord.Net.Core/Entities/Interactions/Modals/ModalBuilder.cs
  src/Discord.Net.Core/Entities/Users/GuildUserProperties.cs
  src/Discord.Net.Core/Entities/Users/IGuildUser.cs
  src/Discord.Net.Core/Utils/UrlValidation.cs
  src/Discord.Net.Interactions/Attributes/AutocompleteAttribute.cs
  src/Discord.Net.Interactions/Attributes/Modals/ModalInputAttribute.cs
  src/Discord.Net.Interactions/Attributes/Modals/ModalTextInputAttribute.cs
  src/Discord.Net.Interactions/Attributes/Preconditions/RequireUserPermissionAttribute.cs
  src/Discord.Net.Interactions/Builders/Commands/SlashCommandBuilder.cs
  src/Discord.Net.Interactions/Builders/Modals/Inputs/TextInputComponentBuilder.cs
  src/Discord.Net.Interactions/Builders/Modals/ModalBuilder.cs
  src/Discord.Net.Interactions/Builders/ModuleBuilder.cs
  src/Discord.Net.Interactions/Builders/Parameters/ParameterBuilder.cs
  src/Discord.Net.Interactions/Discord.Net.Interactions.csproj
  src/Discord.Net.Interactions/InteractionContext.cs
  src/Discord.Net.Interactions/InteractionModuleBase.cs
  src/Discord.Net.Interactions/InteractionService.cs
  src/Discord.Net.Interactions/RestInteractionModuleBase.cs
  src/Discord.Net.Interactions/Results/TypeConverterResult.cs
  src/Discord.Net.Rest/Discord.Net.Rest.csproj
  src/Discord.Net.Rest/Entities/Guilds/RestGuild.cs
  src/Discord.Net.Rest/Entities/Interactions/RestInteraction.cs
  src/Discord.Net.Rest/Entities/Roles/RestRole.cs
  src/Discord.Net.Rest/Net/ED25519/CryptoBytes.cs
  src/Discord.Net.Rest/Net/Queue/RequestQueue.cs
  src/Discord.Net.WebSocket/Discord.Net.WebSocket.csproj
  src/Discord.Net.WebSocket/Entities/Guilds/SocketGuild.cs
  src/Discord.Net.Webhook/Discord.Net.Webhook.csproj
Labels: enhancement, lib feature

#2269 feature: Text-In-Voice
  src/Discord.Net.Core/Entities/Channels/IVoiceChannel.cs
  src/Discord.Net.Rest/Entities/Channels/RestStageChannel.cs
  src/Discord.Net.Rest/Entities/Channels/RestTextChannel.cs
  src/Discord.Net.Rest/Entities/Channels/RestVoiceChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketGuildChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketStageChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketTextChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketVoiceChannel.cs
  test/Discord.Net.Tests.Unit/MockedEntities/MockedVoiceChannel.cs
Labels: enhancement, discord feature

#2291 Added threads support to Webhooks
  src/Discord.Net.Rest/DiscordRestApiClient.cs
  src/Discord.Net.Webhook/DiscordWebhookClient.cs
  src/Discord.Net.Webhook/WebhookClientHelper.cs
Labels: enhancement, project: rest

#2307 Add Nullable ComponentTypeConverter and TypeReader
  src/Discord.Net.Interactions/InteractionService.cs
  src/Discord.Net.Interactions/TypeConverters/ComponentInteractions/NullableComponentConverter.cs
  src/Discord.Net.Interactions/TypeReaders/NullableReader.cs
Labels: enhancement, priority: improvement, project: interaction

#2288 [Docs] Autocomplete examples
  docs/guides/int_framework/autocompletion.md
  docs/guides/int_framework/samples/autocompletion/autocomplete-example.cs
  docs/guides/int_framework/samples/intro/autocomplete.cs
Labels: project: docs

#2281 Introduce optional API calling to RestInteraction
  src/Discord.Net.Rest/DiscordRestClient.cs
  src/Discord.Net.Rest/DiscordRestConfig.cs
  src/Discord.Net.Rest/Entities/Interactions/CommandBase/RestCommandBase.cs
  src/Discord.Net.Rest/Entities/Interactions/CommandBase/RestCommandBaseData.cs
  src/Discord.Net.Rest/Entities/Interactions/CommandBase/RestResolvableData.cs
  src/Discord.Net.Rest/Entities/Interactions/ContextMenuCommands/MessageCommands/RestMessageCommand.cs
  src/Discord.Net.Rest/Entities/Interactions/ContextMenuCommands/MessageCommands/RestMessageCommandData.cs
  src/Discord.Net.Rest/Entities/Interactions/ContextMenuCommands/UserCommands/RestUserCommand.cs
  src/Discord.Net.Rest/Entities/Interactions/ContextMenuCommands/UserCommands/RestUserCommandData.cs
  src/Discord.Net.Rest/Entities/Interactions/MessageComponents/RestMessageComponent.cs
  src/Discord.Net.Rest/Entities/Interactions/Modals/RestModal.cs
  src/Discord.Net.Rest/Entities/Interactions/RestInteraction.cs
  src/Discord.Net.Rest/Entities/Interactions/RestPingInteraction.cs
  src/Discord.Net.Rest/Entities/Interactions/SlashCommands/RestAutocompleteInteraction.cs
  src/Discord.Net.Rest/Entities/Interactions/SlashCommands/RestSlashCommand.cs
  src/Discord.Net.Rest/Entities/Interactions/SlashCommands/RestSlashCommandData.cs
  src/Discord.Net.Rest/Entities/Users/RestGuildUser.cs
Labels: enhancement, priority: improvement, project: interaction

#2284 Add Parse & TryParse to EmbedBuilder & Add ToJsonString extension
  src/Discord.Net.Core/Entities/Messages/EmbedBuilder.cs
  src/Discord.Net.Rest/Extensions/StringExtensions.cs
Labels: enhancement, priority: improvement

#2313 fix: Upload file size limit
  src/Discord.Net.Rest/AssemblyInfo.cs
  src/Discord.Net.Rest/Entities/Guilds/GuildHelper.cs
  test/Discord.Net.Tests.Integration/Discord.Net.Tests.Integration.csproj
  test/Discord.Net.Tests.Integration/DiscordRestApiClientTests.cs
  test/Discord.Net.Tests.Unit/Discord.Net.Tests.Unit.csproj
  test/Discord.Net.Tests.Unit/GuildHelperTests.cs
Labels: bug

#2319 fix: Use IDiscordClient.GetUserAsync in DiscordSocketClient to use Cached users
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
Labels: enhancement

#2320 fix: NRE with bot scope and user parameters
  src/Discord.Net.WebSocket/Entities/Interaction/SocketBaseCommand/SocketResolvableData.cs
Labels: bug

#2325 Add missing interaction properties
  src/Discord.Net.Core/Entities/Interactions/IDiscordInteraction.cs
  src/Discord.Net.Rest/Entities/Interactions/RestInteraction.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketInteraction.cs
Labels: enhancement

#2331 fix: NRE with Cacheable.DownloadAsync()
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
Labels: priority: critical

#2329 Fixes voice perms not retaining text perms.
  src/Discord.Net.Core/Entities/Permissions/ChannelPermissions.cs
Labels: priority: critical

#2330 Better call control in ParseHttpInteraction
  src/Discord.Net.Rest/DiscordRestClient.cs
  src/Discord.Net.Rest/Entities/Interactions/InteractionProperties.cs
Labels: priority: improvement

#2261 Add per-request header support to Rest requests
  src/Discord.Net.Core/Net/Rest/IRestClient.cs
  src/Discord.Net.Core/RequestOptions.cs
  src/Discord.Net.Rest/Net/DefaultRestClient.cs
  src/Discord.Net.Rest/Net/Queue/Requests/RestRequest.cs
Labels: enhancement, project: rest, version: major
