Repository discord-net/Discord.Net, pull requests merged in 2022-03, with the labels that each got.

#2146 Add DateTimeOffset in TimestampTag
  src/Discord.Net.Core/Entities/Messages/TimestampTag.cs
Labels: enhancement

#2135 Fix NRE when ratelimmited requests don't return a body
  src/Discord.Net.Rest/Net/Queue/RequestQueueBucket.cs
Labels: priority: critical

#2128 Fix context menu comand message type
  src/Discord.Net.WebSocket/Entities/Messages/SocketMessage.cs
Labels: bug

#2127 Fixed documentation typo's
  docs/guides/int_basics/message-components/advanced.md
  docs/guides/int_basics/message-components/text-input.md
  docs/guides/int_framework/samples/intro/context.cs
Labels: project: docs

#2134 Guides for Serilog and EFCore
  docs/guides/other_libs/efcore.md
  docs/guides/other_libs/images/serilog_output.png
  docs/guides/other_libs/samples/ConfiguringSerilog.cs
  docs/guides/other_libs/samples/DbContextDepInjection.cs
  docs/guides/other_libs/samples/DbContextSample.cs
  docs/guides/other_libs/samples/InteractionModuleDISample.cs
  docs/guides/other_libs/samples/LogDebugSample.cs
  docs/guides/other_libs/samples/ModifyLogMethod.cs
  docs/guides/other_libs/serilog.md
  docs/guides/toc.yml
Labels: project: docs

#2119 Fixed typos
  docs/guides/int_basics/application-commands/slash-commands/creating-slash-commands.md
Labels: project: docs

#2062 Add return statement to precondition handling
  src/Discord.Net.Commands/CommandService.cs
Labels: enhancement

#2137 Add self_video to VoiceState
  src/Discord.Net.Core/Entities/Users/IVoiceState.cs
  src/Discord.Net.Rest/API/Common/VoiceState.cs
  src/Discord.Net.Rest/Entities/Users/RestGroupUser.cs
  src/Discord.Net.Rest/Entities/Users/RestGuildUser.cs
  src/Discord.Net.Rest/Entities/Users/RestWebhookUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketGroupUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketGuildUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketThreadUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketVoiceState.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketWebhookUser.cs
Labels: enhancement

#2149 Clarify Users property on SocketGuildChannel
  src/Discord.Net.WebSocket/Entities/Channels/SocketGuildChannel.cs
Labels: enhancement

#2151 Add Image property to Guild Scheduled Events
  src/Discord.Net.Core/CDN.cs
  src/Discord.Net.Core/Entities/Guilds/GuildScheduledEventsProperties.cs
  src/Discord.Net.Core/Entities/Guilds/IGuild.cs
  src/Discord.Net.Core/Entities/Guilds/IGuildScheduledEvent.cs
  src/Discord.Net.Rest/API/Common/GuildScheduledEvent.cs
  src/Discord.Net.Rest/API/Rest/CreateGuildScheduledEventParams.cs
  src/Discord.Net.Rest/API/Rest/ModifyGuildScheduledEventParams.cs
  src/Discord.Net.Rest/Entities/Guilds/GuildHelper.cs
  src/Discord.Net.Rest/Entities/Guilds/RestGuild.cs
  src/Discord.Net.Rest/Entities/Guilds/RestGuildEvent.cs
  src/Discord.Net.WebSocket/Entities/Guilds/SocketGuild.cs
  src/Discord.Net.WebSocket/Entities/Guilds/SocketGuildEvent.cs
Labels: enhancement, discord feature

#2153 Add IsInvitable and CreatedAt to threads
  src/Discord.Net.Core/Entities/Channels/IThreadChannel.cs
  src/Discord.Net.Rest/API/Common/ThreadMetadata.cs
  src/Discord.Net.Rest/Entities/Channels/RestChannel.cs
  src/Discord.Net.Rest/Entities/Channels/RestThreadChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketThreadChannel.cs
Labels: enhancement, discord feature

#2154 Fix usage of CacheMode.AllowDownload in channels
  src/Discord.Net.Core/Entities/Channels/IChannel.cs
  src/Discord.Net.Rest/Entities/Channels/RestGuildChannel.cs
  src/Discord.Net.Rest/Entities/Channels/RestTextChannel.cs
  src/Discord.Net.WebSocket/BaseSocketClient.cs
  src/Discord.Net.WebSocket/DiscordShardedClient.cs
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketCategoryChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketGroupChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketGuildChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketTextChannel.cs
  src/Discord.Net.WebSocket/Entities/Guilds/SocketGuild.cs
Labels: enhancement

#2131 Support Sending Message Flags
  src/Discord.Net.Core/Entities/Channels/IMessageChannel.cs
  src/Discord.Net.Rest/API/Rest/CreateMessageParams.cs
  src/Discord.Net.Rest/Entities/Channels/ChannelHelper.cs
  src/Discord.Net.Rest/Entities/Channels/IRestMessageChannel.cs
  src/Discord.Net.Rest/Entities/Channels/RestDMChannel.cs
  src/Discord.Net.Rest/Entities/Channels/RestGroupChannel.cs
  src/Discord.Net.Rest/Entities/Channels/RestTextChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/ISocketMessageChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketDMChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketGroupChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketTextChannel.cs
  src/Discord.Net.Webhook/DiscordWebhookClient.cs
  src/Discord.Net.Webhook/WebhookClientHelper.cs
  test/Discord.Net.Tests.Unit/MockedEntities/MockedDMChannel.cs
  test/Discord.Net.Tests.Unit/MockedEntities/MockedGroupChannel.cs
  test/Discord.Net.Tests.Unit/MockedEntities/MockedTextChannel.cs
Labels: enhancement, blocked, version: minor

#2155 Interaction Service Complex Parameters
  src/Discord.Net.Interactions/Attributes/ComplexParameterAttribute.cs
  src/Discord.Net.Interactions/Attributes/ComplexParameterCtorAttribute.cs
  src/Discord.Net.Interactions/Builders/ModuleClassBuilder.cs
  src/Discord.Net.Interactions/Builders/Parameters/SlashCommandParameterBuilder.cs
  src/Discord.Net.Interactions/Info/Commands/CommandInfo.cs
  src/Discord.Net.Interactions/Info/Commands/SlashCommandInfo.cs
  src/Discord.Net.Interactions/Info/Parameters/SlashCommandParameterInfo.cs
  src/Discord.Net.Interactions/InteractionService.cs
  src/Discord.Net.Interactions/Results/ParseResult.cs
  src/Discord.Net.Interactions/Utilities/ApplicationCommandRestUtil.cs
Labels: enhancement, version: minor, project: interaction

#2156 Display name support for enum type converter
  docs/guides/int_framework/samples/intro/groupattribute.cs
  samples/InteractionFramework/ExampleEnum.cs
  src/Discord.Net.Interactions/Attributes/EnumChoiceAttribute.cs
  src/Discord.Net.Interactions/TypeConverters/EnumConverter.cs
Labels: enhancement

#2157 Enforce valid button styles
  src/Discord.Net.Core/Entities/Interactions/MessageComponents/ComponentBuilder.cs
Labels: enhancement

#2158 Unneeded build event
  docs/guides/int_basics/application-commands/slash-commands/choice-slash-command.md
Labels: project: docs

#2160 Create Complex Params Docs
  docs/guides/int_framework/intro.md
  docs/guides/int_framework/samples/intro/complexparams.cs
Labels: project: interaction

#2162 Add configuration toggle to suppress Unknown dispatch warnings
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
  src/Discord.Net.WebSocket/DiscordSocketConfig.cs
Labels: enhancement

#2169 Component TypeConverters and CustomID TypeReaders
  src/Discord.Net.Interactions/Builders/Commands/ComponentCommandBuilder.cs
  src/Discord.Net.Interactions/Builders/Modals/Inputs/IInputComponentBuilder.cs
  src/Discord.Net.Interactions/Builders/Modals/Inputs/InputComponentBuilder.cs
  src/Discord.Net.Interactions/Builders/Modals/ModalBuilder.cs
  src/Discord.Net.Interactions/Builders/ModuleClassBuilder.cs
  src/Discord.Net.Interactions/Builders/Parameters/ComponentCommandParameterBuilder.cs
  src/Discord.Net.Interactions/Builders/Parameters/ModalCommandParameterBuilder.cs
  src/Discord.Net.Interactions/Entities/ITypeConverter.cs
  src/Discord.Net.Interactions/Info/Commands/AutocompleteCommandInfo.cs
  src/Discord.Net.Interactions/Info/Commands/CommandInfo.cs
  src/Discord.Net.Interactions/Info/Commands/ComponentCommandInfo.cs
  src/Discord.Net.Interactions/Info/Commands/ModalCommandInfo.cs
  src/Discord.Net.Interactions/Info/Commands/SlashCommandInfo.cs
  src/Discord.Net.Interactions/Info/InputComponents/InputComponentInfo.cs
  src/Discord.Net.Interactions/Info/ModalInfo.cs
  src/Discord.Net.Interactions/Info/Parameters/ComponentCommandParameterInfo.cs
  src/Discord.Net.Interactions/Info/Parameters/ModalCommandParameterInfo.cs
  src/Discord.Net.Interactions/InteractionService.cs
  src/Discord.Net.Interactions/InteractionServiceConfig.cs
  src/Discord.Net.Interactions/Map/TypeMap.cs
  src/Discord.Net.Interactions/TypeConverters/ComponentInteractions/ComponentTypeConverter.cs
  src/Discord.Net.Interactions/TypeConverters/ComponentInteractions/DefaultArrayComponentConverter.cs
  src/Discord.Net.Interactions/TypeConverters/ComponentInteractions/DefaultValueComponentConverter.cs
  src/Discord.Net.Interactions/TypeConverters/SlashCommands/DefaultEntityTypeConverter.cs
  src/Discord.Net.Interactions/TypeConverters/SlashCommands/DefaultValueConverter.cs
  src/Discord.Net.Interactions/TypeConverters/SlashCommands/EnumConverter.cs
  src/Discord.Net.Interactions/TypeConverters/SlashCommands/NullableConverter.cs
  src/Discord.Net.Interactions/TypeConverters/SlashCommands/TimeSpanConverter.cs
  src/Discord.Net.Interactions/TypeConverters/SlashCommands/TypeConverter.cs
  src/Discord.Net.Interactions/TypeReaders/DefaultSnowflakeReader.cs
  src/Discord.Net.Interactions/TypeReaders/DefaultValueReader.cs
  src/Discord.Net.Interactions/TypeReaders/EnumReader.cs
  src/Discord.Net.Interactions/TypeReaders/TypeReader.cs
  src/Discord.Net.Interactions/Utilities/ModalUtils.cs
Labels: enhancement

#2179 Fix: sharded client logout throws
  src/Discord.Net.WebSocket/DiscordShardedClient.cs
Labels: bug

#2180 Feature: attachment description and content type
  src/Discord.Net.Core/Entities/Messages/FileAttachment.cs
  src/Discord.Net.Core/Entities/Messages/IAttachment.cs
  src/Discord.Net.Rest/Entities/Messages/Attachment.cs
Labels: enhancement

#2181 Fix/ambigiuous reference
  src/Discord.Net.Rest/Entities/Guilds/RestGuild.cs
  src/Discord.Net.WebSocket/Entities/Guilds/SocketGuild.cs
Labels: bug, enhancement

#2182 fix: thread owner always null
  src/Discord.Net.WebSocket/Entities/Channels/SocketThreadChannel.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketThreadUser.cs
Labels: bug

#2168 Fixed Integration model from GuildIntegration and added INTEGRATION gateway events
  src/Discord.Net.Core/Entities/Guilds/GuildIntegrationProperties.cs
  src/Discord.Net.Core/Entities/Guilds/IGuild.cs
  src/Discord.Net.Core/Entities/Guilds/IntegrationAccount.cs
  src/Discord.Net.Core/Entities/Integrations/IIntegration.cs
  src/Discord.Net.Core/Entities/Integrations/IIntegrationAccount.cs
  src/Discord.Net.Core/Entities/Integrations/IIntegrationApplication.cs
  src/Discord.Net.Core/Entities/Integrations/IntegrationExpireBehavior.cs
  src/Discord.Net.Core/Entities/Users/ConnectionVisibility.cs
  src/Discord.Net.Core/Entities/Users/IConnection.cs
  src/Discord.Net.Rest/API/Common/Connection.cs
  src/Discord.Net.Rest/API/Common/Integration.cs
  src/Discord.Net.Rest/API/Common/IntegrationAccount.cs
  src/Discord.Net.Rest/API/Common/IntegrationApplication.cs
  src/Discord.Net.Rest/ClientHelper.cs
  src/Discord.Net.Rest/DiscordRestApiClient.cs
  src/Discord.Net.Rest/Entities/Guilds/GuildHelper.cs
  src/Discord.Net.Rest/Entities/Guilds/RestGuild.cs
  src/Discord.Net.Rest/Entities/Guilds/RestGuildIntegration.cs
  src/Discord.Net.Rest/Entities/Integrations/RestIntegration.cs
  src/Discord.Net.Rest/Entities/Integrations/RestIntegrationAccount.cs
  src/Discord.Net.Rest/Entities/Integrations/RestIntegrationApplication.cs
  src/Discord.Net.Rest/Entities/Users/RestConnection.cs
  src/Discord.Net.WebSocket/API/Gateway/IntegrationDeletedEvent.cs
  src/Discord.Net.WebSocket/BaseSocketClient.Events.cs
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
  src/Discord.Net.WebSocket/Entities/Guilds/SocketGuild.cs
Labels: enhancement, discord feature

#2210 Add a way to remove type readers from the interaction/command service.
  src/Discord.Net.Commands/CommandService.cs
  src/Discord.Net.Interactions/InteractionService.cs
  src/Discord.Net.Interactions/Map/TypeMap.cs
Labels: enhancement, project: interaction

#2219 Fix ShardedClients not pushing PresenceUpdates
  src/Discord.Net.WebSocket/DiscordShardedClient.cs
Labels: priority: critical
