Repository discord-net/Discord.Net, pull requests merged in 2022-12, with the labels that each got.

#2526 [feature-ish] Fix `GetActiveThreadsAsync` & add it to `ITextChannel`
  src/Discord.Net.Core/Entities/Channels/ITextChannel.cs
  src/Discord.Net.Rest/Entities/Channels/RestForumChannel.cs
  src/Discord.Net.Rest/Entities/Channels/RestTextChannel.cs
  src/Discord.Net.Rest/Entities/Channels/RestThreadChannel.cs
  src/Discord.Net.Rest/Entities/Channels/RestVoiceChannel.cs
  src/Discord.Net.Rest/Entities/Channels/ThreadHelper.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketForumChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketTextChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketThreadChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketVoiceChannel.cs
  test/Discord.Net.Tests.Unit/MockedEntities/MockedTextChannel.cs
Labels: bug

#2521 [Feature] Add missing property & new stuff
  src/Discord.Net.Core/DiscordErrorCode.cs
  src/Discord.Net.Core/Entities/ApplicationFlags.cs
  src/Discord.Net.Core/Entities/Channels/ForumChannelProperties.cs
  src/Discord.Net.Core/Entities/Channels/ForumLayout.cs
  src/Discord.Net.Core/Entities/Channels/IForumChannel.cs
  src/Discord.Net.Core/Entities/Channels/IThreadChannel.cs
  src/Discord.Net.Core/Entities/Users/UserProperties.cs
  src/Discord.Net.Rest/API/Common/Channel.cs
  src/Discord.Net.Rest/API/Rest/ModifyForumChannelParams.cs
  src/Discord.Net.Rest/Entities/Channels/ForumHelper.cs
  src/Discord.Net.Rest/Entities/Channels/RestForumChannel.cs
  src/Discord.Net.Rest/Entities/Channels/RestThreadChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketForumChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketThreadChannel.cs
Labels: enhancement

#2520 Implemented ClientDisconnected event for audio client.
  src/Discord.Net.Core/Audio/IAudioClient.cs
  src/Discord.Net.WebSocket/API/Voice/ClientDisconnectEvent.cs
  src/Discord.Net.WebSocket/Audio/AudioClient.Events.cs
  src/Discord.Net.WebSocket/Audio/AudioClient.cs
Labels: enhancement, lib feature

#2509 Add SendFiles to UserExtensions
  src/Discord.Net.Core/Extensions/UserExtensions.cs
  src/Discord.Net.Rest/Entities/Channels/IRestMessageChannel.cs
  src/Discord.Net.WebSocket/Entities/Channels/ISocketMessageChannel.cs
Labels: enhancement

#2528 CustomID Template Improvements
  src/Discord.Net.Interactions/Attributes/Commands/ComponentInteractionAttribute.cs
  src/Discord.Net.Interactions/Attributes/Commands/ModalInteractionAttribute.cs
  src/Discord.Net.Interactions/Builders/Commands/CommandBuilder.cs
  src/Discord.Net.Interactions/Builders/Commands/ICommandBuilder.cs
  src/Discord.Net.Interactions/Builders/ModuleClassBuilder.cs
  src/Discord.Net.Interactions/Info/Commands/CommandInfo.cs
  src/Discord.Net.Interactions/Info/ICommandInfo.cs
  src/Discord.Net.Interactions/Map/CommandMapNode.cs
  src/Discord.Net.Interactions/Utilities/RegexUtils.cs
Labels: enhancement, lib feature, project: interaction

#2510 [Feature] add missing invite guild properties & welcome screen support
  src/Discord.Net.Core/Entities/Guilds/IGuild.cs
  src/Discord.Net.Core/Entities/Guilds/WelcomeScreen.cs
  src/Discord.Net.Core/Entities/Guilds/WelcomeScreenChannel.cs
  src/Discord.Net.Core/Entities/Guilds/WelcomeScreenChannelProperties.cs
  src/Discord.Net.Core/Entities/Invites/IInvite.cs
  src/Discord.Net.Core/Entities/Invites/InviteGuild.cs
  src/Discord.Net.Rest/API/Common/Guild.cs
  src/Discord.Net.Rest/API/Common/InviteGuild.cs
  src/Discord.Net.Rest/API/Common/WelcomeScreen.cs
  src/Discord.Net.Rest/API/Common/WelcomeScreenChannel.cs
  src/Discord.Net.Rest/API/Rest/ModifyGuildWelcomeScreenParams.cs
  src/Discord.Net.Rest/DiscordRestApiClient.cs
  src/Discord.Net.Rest/Entities/Guilds/GuildHelper.cs
  src/Discord.Net.Rest/Entities/Guilds/RestGuild.cs
  src/Discord.Net.Rest/Entities/Invites/RestInvite.cs
  src/Discord.Net.WebSocket/Entities/Guilds/SocketGuild.cs
Labels: enhancement
