Repository discord-net/Discord.Net, pull requests merged in 2023-08, with the labels that each got.

#2749 [Feature] Support for setting custom status
  src/Discord.Net.Core/Entities/Activities/CustomStatusGame.cs
  src/Discord.Net.WebSocket/BaseSocketClient.cs
  src/Discord.Net.WebSocket/DiscordShardedClient.cs
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
Labels: enhancement, discord feature

#2711 [Fix] Modifying guild resets preferred locale
  src/Discord.Net.Rest/API/Rest/ModifyGuildParams.cs
Labels: priority: bug

#2719 [Fix] Forum channel related issues.
  src/Discord.Net.Core/Entities/Channels/ForumChannelProperties.cs
  src/Discord.Net.Core/Entities/ForumTags/ForumTag.cs
  src/Discord.Net.Core/Entities/ForumTags/ForumTagBuilder.cs
  src/Discord.Net.Core/Entities/ForumTags/ForumTagProperties.cs
  src/Discord.Net.Core/Entities/ForumTags/IForumTag.cs
  src/Discord.Net.Rest/API/Rest/CreateMultipartPostAsync.cs
  src/Discord.Net.Rest/Entities/Channels/ForumHelper.cs
  src/Discord.Net.Rest/Entities/Channels/ThreadHelper.cs
  src/Discord.Net.Rest/Entities/Guilds/GuildHelper.cs
Labels: enhancement, priority: bug

#2722 [Fix] Update modal's `DeferAsync` impl
  src/Discord.Net.Core/Entities/Interactions/Modals/IModalInteraction.cs
  src/Discord.Net.Rest/Entities/Interactions/Modals/RestModal.cs
  src/Discord.Net.WebSocket/Entities/Interaction/Modals/SocketModal.cs
Labels: enhancement, priority: bug

#2736 [Docs] Add interaction response schemes
  docs/faq/int_framework/images/response-scheme-component.png
  docs/faq/int_framework/images/response-scheme-modal.png
  docs/faq/int_framework/images/response-scheme-slash.png
  docs/faq/int_framework/respondings-schemes.md
  docs/faq/toc.yml
Labels: project: docs, priority: improvement

#2726 [Fix] Updated global name not being passed to `UserUpdated` event
  src/Discord.Net.WebSocket/Entities/Users/SocketGlobalUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketGroupUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketGuildUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketSelfUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketThreadUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketUnknownUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketUser.cs
  src/Discord.Net.WebSocket/Entities/Users/SocketWebhookUser.cs
Labels: priority: bug

#2713 [Fix] some `ReplyAsync` methods missing `MessageFlags` parameter
  src/Discord.Net.Commands/ModuleBase.cs
  src/Discord.Net.Core/Extensions/MessageExtensions.cs
  src/Discord.Net.Interactions/InteractionModuleBase.cs
Labels: enhancement

#2729 [Feature] Onboarding updates
  src/Discord.Net.Core/DiscordErrorCode.cs
  src/Discord.Net.Core/Entities/Guilds/IGuild.cs
  src/Discord.Net.Core/Entities/Guilds/Onboarding/GuildOnboardingMode.cs
  src/Discord.Net.Core/Entities/Guilds/Onboarding/GuildOnboardingPromptOptionProperties.cs
  src/Discord.Net.Core/Entities/Guilds/Onboarding/GuildOnboardingPromptProperties.cs
  src/Discord.Net.Core/Entities/Guilds/Onboarding/GuildOnboardingProperties.cs
  src/Discord.Net.Core/Entities/Guilds/Onboarding/IGuildOnboarding.cs
  src/Discord.Net.Core/Extensions/GuildOnboardingExtensions.cs
  src/Discord.Net.Rest/API/Common/GuildOnboarding.cs
  src/Discord.Net.Rest/API/Common/GuildOnboardingPromptOption.cs
  src/Discord.Net.Rest/API/Rest/ModifyGuildOnboardingParams.cs
  src/Discord.Net.Rest/DiscordRestApiClient.cs
  src/Discord.Net.Rest/Entities/Guilds/GuildHelper.cs
  src/Discord.Net.Rest/Entities/Guilds/Onboarding/RestGuildOnboarding.cs
  src/Discord.Net.Rest/Entities/Guilds/Onboarding/RestGuildOnboardingPromptOption.cs
  src/Discord.Net.Rest/Entities/Guilds/RestGuild.cs
  src/Discord.Net.WebSocket/Entities/Guilds/Onboarding/SocketGuildOnboarding.cs
  src/Discord.Net.WebSocket/Entities/Guilds/Onboarding/SocketGuildOnboardingPromptOption.cs
  src/Discord.Net.WebSocket/Entities/Guilds/SocketGuild.cs
Labels: discord feature, priority: improvement

#2712 [Refactor] Remove unnecessary `@everyone` role check
  src/Discord.Net.Rest/DiscordRestApiClient.cs
Labels: priority: improvement

#2723 [Feature] Update webhook implementation
  src/Discord.Net.Core/Entities/Webhooks/IWebhook.cs
  src/Discord.Net.Core/Entities/Webhooks/WebhookType.cs
  src/Discord.Net.Rest/API/Common/Webhook.cs
  src/Discord.Net.Rest/Entities/Webhooks/RestWebhook.cs
  src/Discord.Net.Webhook/Entities/Webhooks/RestInternalWebhook.cs
Labels: discord feature, priority: improvement

#2730 [Feature] New `ModifyCurrentApplication` features
  src/Discord.Net.Core/DiscordConfig.cs
  src/Discord.Net.Core/Entities/Applications/ApplicationFlags.cs
  src/Discord.Net.Core/Entities/Applications/ApplicationInstallParams.cs
  src/Discord.Net.Core/Entities/Applications/IApplication.cs
  src/Discord.Net.Core/Entities/Applications/ModifyApplicationProperties.cs
  src/Discord.Net.Rest/API/Common/InstallParams.cs
  src/Discord.Net.Rest/API/Rest/ModifyCurrentApplicationBotParams.cs
  src/Discord.Net.Rest/ClientHelper.cs
  src/Discord.Net.Rest/Entities/RestApplication.cs
Labels: discord feature, priority: improvement

#2714 [Fix] Disconnecting socket client does not send close code
  src/Discord.Net.WebSocket/DiscordSocketApiClient.cs
  src/Discord.Net.WebSocket/Net/DefaultWebSocketClient.cs
Labels: priority: bug

#2654 [Feature] Refactor stage instance implementation
  src/Discord.Net.Core/Entities/Channels/IStageChannel.cs
  src/Discord.Net.Core/Entities/Guilds/IStageInstance.cs
  src/Discord.Net.Rest/API/Common/StageInstance.cs
  src/Discord.Net.Rest/API/Rest/CreateStageInstanceParams.cs
  src/Discord.Net.Rest/ClientHelper.cs
  src/Discord.Net.Rest/DiscordRestApiClient.cs
  src/Discord.Net.Rest/DiscordRestClient.cs
  src/Discord.Net.Rest/Entities/Channels/ChannelHelper.cs
  src/Discord.Net.Rest/Entities/Channels/RestStageChannel.cs
  src/Discord.Net.Rest/Entities/Guilds/RestStageInstance.cs
  src/Discord.Net.WebSocket/API/Gateway/ExtendedGuild.cs
  src/Discord.Net.WebSocket/BaseSocketClient.Events.cs
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
  src/Discord.Net.WebSocket/Entities/Channels/SocketStageChannel.cs
  src/Discord.Net.WebSocket/Entities/Guilds/SocketGuild.cs
  src/Discord.Net.WebSocket/Entities/Guilds/SocketStageInstance.cs
Labels: version: major

#2761 [docs] fixed typo
  docs/index.md
Labels: project: docs
