Repository discord-net/Discord.Net, pull requests merged in 2023-09, with the labels that each got.

#2773 [Feature] Add useful utility methods to `ModalBuilder`
  src/Discord.Net.Core/Entities/Interactions/Modals/ModalBuilder.cs
Labels: enhancement, lib feature, priority: improvement

#2774 [Fix] Some IDiscordClient methods are not properly implemented in clients
  src/Discord.Net.Rest/DiscordRestClient.cs
  src/Discord.Net.WebSocket/DiscordShardedClient.cs
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
Labels: lib feature, priority: improvement

#2781 [Feature] Premium subscriptions
  src/Discord.Net.Core/DiscordConfig.cs
  src/Discord.Net.Core/Entities/AppSubscriptions/EntitlementType.cs
  src/Discord.Net.Core/Entities/AppSubscriptions/IEntitlement.cs
  src/Discord.Net.Core/Entities/AppSubscriptions/SKU.cs
  src/Discord.Net.Core/Entities/AppSubscriptions/SKUFlags.cs
  src/Discord.Net.Core/Entities/AppSubscriptions/SKUType.cs
  src/Discord.Net.Core/Entities/AppSubscriptions/SubscriptionOwnerType.cs
  src/Discord.Net.Core/Entities/Interactions/IDiscordInteraction.cs
  src/Discord.Net.Core/Entities/Interactions/InteractionResponseType.cs
  src/Discord.Net.Core/IDiscordClient.cs
  src/Discord.Net.Interactions/InteractionModuleBase.cs
  src/Discord.Net.Rest/API/Common/Entitlement.cs
  src/Discord.Net.Rest/API/Common/Interaction.cs
  src/Discord.Net.Rest/API/Common/SKU.cs
  src/Discord.Net.Rest/API/Rest/CreateEntitlementParams.cs
  src/Discord.Net.Rest/API/Rest/ListEntitlementsParams.cs
  src/Discord.Net.Rest/BaseDiscordClient.cs
  src/Discord.Net.Rest/ClientHelper.cs
  src/Discord.Net.Rest/DiscordRestApiClient.cs
  src/Discord.Net.Rest/DiscordRestClient.cs
  src/Discord.Net.Rest/Entities/AppSubscriptions/RestEntitlement.cs
  src/Discord.Net.Rest/Entities/Interactions/InteractionHelper.cs
  src/Discord.Net.Rest/Entities/Interactions/RestInteraction.cs
  src/Discord.Net.WebSocket/BaseSocketClient.Events.cs
  src/Discord.Net.WebSocket/ClientState.cs
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
  src/Discord.Net.WebSocket/Entities/AppSubscriptions/SocketEntitlement.cs
  src/Discord.Net.WebSocket/Entities/Interaction/SocketInteraction.cs
Labels: discord feature, priority: improvement
