Repository discord-net/Discord.Net, pull requests merged in 2024-02, with the labels that each got.

#2835 [Feature] Moar select menu option validations
  src/Discord.Net.Core/Entities/Interactions/MessageComponents/ComponentBuilder.cs
Labels: enhancement, lib feature

#2837 [Feature] Allow creating announcement channels & modifying channel type of text & news channels
  src/Discord.Net.Core/Entities/Channels/TextChannelProperties.cs
  src/Discord.Net.Core/Entities/Guilds/IGuild.cs
  src/Discord.Net.Rest/API/Rest/ModifyTextChannelParams.cs
  src/Discord.Net.Rest/Entities/Channels/ChannelHelper.cs
  src/Discord.Net.Rest/Entities/Guilds/GuildHelper.cs
  src/Discord.Net.Rest/Entities/Guilds/RestGuild.cs
  src/Discord.Net.WebSocket/Entities/Guilds/SocketGuild.cs
Labels: discord feature, priority: improvement

#2850 [Fix] NRE in automod audit logs
  src/Discord.Net.Rest/Entities/AuditLogs/DataTypes/AutoModFlaggedMessageAuditLogData.cs
  src/Discord.Net.WebSocket/Entities/AuditLogs/DataTypes/SocketAutoModFlaggedMessageAuditLogData.cs
Labels: priority: bug

#2858 [Feature] Allow setting custom status with `SetGameAsync`
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
Labels: lib feature, priority: improvement

#2857 [Fix] Receiving voice packets (use system-assigned port)
  src/Discord.Net.WebSocket/Audio/AudioClient.cs
  src/Discord.Net.WebSocket/DiscordVoiceApiClient.cs
  src/Discord.Net.WebSocket/Entities/Guilds/SocketGuild.cs
Labels: project: audio, priority: improvement

#2860 [Docs] Update sending-voice.md
  .github/workflows/dotnet.yml
  docs/guides/voice/sending-voice.md
Labels: project: docs

#2849 [Fix] Allow setting channel topic to null when creating channels
  .github/workflows/dotnet.yml
  src/Discord.Net.Rest/DiscordRestApiClient.cs
Labels: lib feature, priority: bug

#2832 [Feature] Add Icon size parameter to `GetGuildIconUrl` CDN method
  .github/workflows/dotnet.yml
  src/Discord.Net.Core/CDN.cs
Labels: enhancement, lib feature

#2847 [Docs] Remove some redundant notes & small updates
  .github/workflows/docs.yml
  README.md
  docs/faq/int_framework/general.md
  docs/guides/int_basics/application-commands/intro.md
  docs/guides/int_basics/application-commands/slash-commands/creating-slash-commands.md
  docs/guides/int_framework/intro.md
Labels: project: docs

#2865 [Add] example localization to the interaction framework sample
  samples/InteractionFramework/Program.cs
  samples/InteractionFramework/Resources/CommandLocales.Designer.cs
  samples/InteractionFramework/Resources/CommandLocales.resx
  samples/InteractionFramework/Resources/CommandLocales.ru.resx
  samples/InteractionFramework/_InteractionFramework.csproj
Labels: enhancement

#2855 [Fix] Incorrect `ConnectionState` of a `DiscordSocketClient` casted to `IDiscordClient`/`BaseSocketClient`
  src/Discord.Net.Rest/BaseDiscordClient.cs
  src/Discord.Net.WebSocket/DiscordSocketClient.cs
Labels: priority: bug
